
tiny_out:
	java -cp build/classes/ ce326.hw1.HW1 < tests/tiny-i.in    > tests/tiny-i.out
	diff -urN tests/tiny-i.out tests/tiny-i.std
	java -cp build/classes/ ce326.hw1.HW1 < tests/tiny-id.in   > tests/tiny-id.out
	diff -urN tests/tiny-id.out tests/tiny-id.std
	java -cp build/classes/ ce326.hw1.HW1 < tests/tiny-idi.in  > tests/tiny-idi.out
	diff -urN tests/tiny-idi.out tests/tiny-idi.std
	java -cp build/classes/ ce326.hw1.HW1 < tests/tiny-iw-1.in > tests/tiny-iw-1.out
	diff -urN tests/tiny-iw-1.out tests/tiny-iw-1.std
	java -cp build/classes/ ce326.hw1.HW1 < tests/tiny-iw-2.in > tests/tiny-iw-2.out
	diff -urN tests/tiny-iw-2.out tests/tiny-iw-2.std
	java -cp build/classes/ ce326.hw1.HW1 < tests/tiny-iw-3.in > tests/tiny-iw-3.out
	diff -urN tests/tiny-iw-3.out tests/tiny-iw-3.std
	java -cp build/classes/ ce326.hw1.HW1 < tests/tiny-iw-4.in > tests/tiny-iw-4.out
	diff -urN tests/tiny-iw-4.out tests/tiny-iw-4.std
	java -cp build/classes/ ce326.hw1.HW1 < tests/tiny-is-1.in > tests/tiny-is-1.out
	diff -urN tests/tiny-is-1.out tests/tiny-is-1.std
	java -cp build/classes/ ce326.hw1.HW1 < tests/tiny-is-2.in > tests/tiny-is-2.out
	diff -urN tests/tiny-is-2.out tests/tiny-is-2.std
	java -cp build/classes/ ce326.hw1.HW1 < tests/tiny-is-3.in > tests/tiny-is-3.out
	diff -urN tests/tiny-is-3.out tests/tiny-is-3.std

small_out:
	java -cp build/classes/ ce326.hw1.HW1 < tests/small-i.in    > tests/small-i.out
	diff -urN tests/small-i.out tests/small-i.std
	java -cp build/classes/ ce326.hw1.HW1 < tests/small-id.in   > tests/small-id.out
	diff -urN tests/small-id.out tests/small-id.std
	java -cp build/classes/ ce326.hw1.HW1 < tests/small-idi.in  > tests/small-idi.out
	diff -urN tests/small-idi.out tests/small-idi.std
	java -cp build/classes/ ce326.hw1.HW1 < tests/small-iw-1.in > tests/small-iw-1.out
	diff -urN tests/small-iw-1.out tests/small-iw-1.std
	java -cp build/classes/ ce326.hw1.HW1 < tests/small-iw-2.in > tests/small-iw-2.out
	diff -urN tests/small-iw-2.out tests/small-iw-2.std
	java -cp build/classes/ ce326.hw1.HW1 < tests/small-iw-3.in > tests/small-iw-3.out
	diff -urN tests/small-iw-3.out tests/small-iw-3.std
	java -cp build/classes/ ce326.hw1.HW1 < tests/small-is-1.in > tests/small-is-1.out
	diff -urN tests/small-is-1.out tests/small-is-1.std
	java -cp build/classes/ ce326.hw1.HW1 < tests/small-is-2.in > tests/small-is-2.out
	diff -urN tests/small-is-2.out tests/small-is-2.std
	java -cp build/classes/ ce326.hw1.HW1 < tests/small-is-3.in > tests/small-is-3.out
	diff -urN tests/small-is-3.out tests/small-is-3.std
	
large_out:
	java -cp build/classes/ ce326.hw1.HW1 < tests/large-i.in    > tests/large-i.out
	diff -urN tests/large-i.out tests/large-i.std
	java -cp build/classes/ ce326.hw1.HW1 < tests/large-id.in   > tests/large-id.out
	diff -urN tests/large-id.out tests/large-id.std
	java -cp build/classes/ ce326.hw1.HW1 < tests/large-idi.in   > tests/large-idi.out
	diff -urN tests/large-idi.out tests/large-idi.std
	java -cp build/classes/ ce326.hw1.HW1 < tests/large-iw-1.in > tests/large-iw-1.out
	diff -urN tests/large-iw-1.out tests/large-iw-1.std
	java -cp build/classes/ ce326.hw1.HW1 < tests/large-iw-2.in > tests/large-iw-2.out
	diff -urN tests/large-iw-2.out tests/large-iw-2.std
	java -cp build/classes/ ce326.hw1.HW1 < tests/large-is-1.in > tests/large-is-1.out
	diff -urN tests/large-is-1.out tests/large-is-1.std
	java -cp build/classes/ ce326.hw1.HW1 < tests/large-is-2.in > tests/large-is-2.out
	diff -urN tests/large-is-2.out tests/large-is-2.std
	java -cp build/classes/ ce326.hw1.HW1 < tests/large-is-3.in > tests/large-is-3.out
	diff -urN tests/large-is-3.out tests/large-is-3.std

out: tiny_out small_out large_out

tiny_std:
	java -cp build/classes/ ce326.hw1.HW1 < tests/tiny-i.in    > tests/tiny-i.std
	java -cp build/classes/ ce326.hw1.HW1 < tests/tiny-id.in   > tests/tiny-id.std
	java -cp build/classes/ ce326.hw1.HW1 < tests/tiny-idi.in  > tests/tiny-idi.std
	java -cp build/classes/ ce326.hw1.HW1 < tests/tiny-iw-1.in > tests/tiny-iw-1.std
	java -cp build/classes/ ce326.hw1.HW1 < tests/tiny-iw-2.in > tests/tiny-iw-2.std
	java -cp build/classes/ ce326.hw1.HW1 < tests/tiny-iw-3.in > tests/tiny-iw-3.std
	java -cp build/classes/ ce326.hw1.HW1 < tests/tiny-iw-4.in > tests/tiny-iw-4.std
	java -cp build/classes/ ce326.hw1.HW1 < tests/tiny-is-1.in > tests/tiny-is-1.std
	java -cp build/classes/ ce326.hw1.HW1 < tests/tiny-is-2.in > tests/tiny-is-2.std
	java -cp build/classes/ ce326.hw1.HW1 < tests/tiny-is-3.in > tests/tiny-is-3.std

small_std:
	java -cp build/classes/ ce326.hw1.HW1 < tests/small-i.in    > tests/small-i.std
	java -cp build/classes/ ce326.hw1.HW1 < tests/small-id.in   > tests/small-id.std
	java -cp build/classes/ ce326.hw1.HW1 < tests/small-idi.in  > tests/small-idi.std
	java -cp build/classes/ ce326.hw1.HW1 < tests/small-iw-1.in > tests/small-iw-1.std
	java -cp build/classes/ ce326.hw1.HW1 < tests/small-iw-2.in > tests/small-iw-2.std
	java -cp build/classes/ ce326.hw1.HW1 < tests/small-iw-3.in > tests/small-iw-3.std
	java -cp build/classes/ ce326.hw1.HW1 < tests/small-is-1.in > tests/small-is-1.std
	java -cp build/classes/ ce326.hw1.HW1 < tests/small-is-2.in > tests/small-is-2.std
	java -cp build/classes/ ce326.hw1.HW1 < tests/small-is-3.in > tests/small-is-3.std

large_std:
	java -cp build/classes/ ce326.hw1.HW1 < tests/large-i.in    > tests/large-i.std
	java -cp build/classes/ ce326.hw1.HW1 < tests/large-id.in   > tests/large-id.std
	java -cp build/classes/ ce326.hw1.HW1 < tests/large-idi.in  > tests/large-idi.std
	java -cp build/classes/ ce326.hw1.HW1 < tests/large-iw-1.in > tests/large-iw-1.std
	java -cp build/classes/ ce326.hw1.HW1 < tests/large-iw-2.in > tests/large-iw-2.std
	java -cp build/classes/ ce326.hw1.HW1 < tests/large-is-1.in > tests/large-is-1.std
	java -cp build/classes/ ce326.hw1.HW1 < tests/large-is-2.in > tests/large-is-2.std
	java -cp build/classes/ ce326.hw1.HW1 < tests/large-is-3.in > tests/large-is-3.std
	
std: tiny_std small_std large_std

clean:
	-rm tests/*.out

